services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $tokenHmacSecret: '%env(AUTH_TOKEN_HMAC_SECRET)%'
            string $phoenixBaseUrl: '%env(PHOENIX_BASE_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
